apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: FlowSchema
metadata:
  name: manifestwork-fs
spec:
  priorityLevelConfiguration:
    name: workload-high
  matchingPrecedence: 2
  distinguisherMethod:
    type: ByUser
  rules:
  - resourceRules:
    - apiGroups:
      - 'work.open-cluster-management.io'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
    - kind: User
      user:
        name: admin
